import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import BaseLayout from "./base";
import "./global.css";

export const metadata = {
    title: "Welcome to web",
    description: "Generated by create-nx-workspace",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider>
                    <BaseLayout>{children}</BaseLayout>
                </MantineProvider>
            </body>
        </html>
    );
}
